### ISSUE TITLE
Have you considered removing EBCDIC support?

### ISSUE THREAD

**Issue by oliverkwebb** [xyproto/tinyxxd#4]
EBCDIC was a alternative to ASCII that died off sometime in the late 70's.
I have __no__ idea why ViM decided to put in support for it in xxd, but I
doubt that anyone has used it in the last 20-30 years.

If for some insane reason anyone in 2024 would ever need to process EBCDIC,
that's what `iconv` is for.

I'd understand if you didn't wanna break compatibility with ViM by removing
this, but at the same time this feature might as well be what you get when
you look in a dictionary for the definition of "bloat".

Removing this would also make the code considerably smaller and simpler (Probably
faster too since we are removing conditional branches in a loop), if you are
interested, I'd be happy to submit a PR stripping the legacy code out.

**Comment by xyproto** [comment]
I fully agree that EBCDIC is not very useful, but in order to replace ViM as a make dependency in connection with Linux packaging, it is important that tinyxxd is a drop-in replacement.

Perhaps at a later stage.

Feel free to fork this project, though.

Thanks for the question!
