### ISSUE TITLE
The people want a `man` page

### ISSUE THREAD

**Issue by philiptaron** [xyproto/tinyxxd#6]
# Motivation

`tinyxxd` is a wonderful drop-in replacement for `xxd`. But it fails that test today for help: typing `man xxd` or `man tinyxxd` produces nothing.

# Details

Documentation sought for these flags, copied from the `xxd` man page:

- [ ] `-a | -autoskip`
- [ ] `-b | -bits`
- [ ] `-c cols | -cols cols`
- [ ] `-C | -capitalize`
- [ ] `-d` show offset in decimal instead of hex.
- [ ] `-E | -EBCDIC`
- [ ] `-e` Switch to little-endian hex dump.
- [ ] `-g bytes | -groupsize bytes`
- [ ] `-h | -help`
- [ ] `-i | -include`
- [ ] `-l len | -len len`
- [ ] `-n name | -name name`
- [ ] `-o offset`
- [ ] `-p | -ps | -postscript | -plain`
- [ ] `-r | -revert`
- [ ] `-R when`
- [ ] `-seek offset`
- [ ] `-s [+][-]seek`
- [ ] `-u`     Use upper-case hex letters. Default is lower-case.
- [ ] `-v | -version`

Plus whatever seems relevant to include from the upstream `vim` repository.

**Comment by emilazy** [comment]
The Vim distribution ships an `xxd.1` so I think it would be as simple as copying it over and installing it (and minimally tweaking as necessary).
