### ISSUE TITLE
Provide advice in the README about aliasing `xxd`

### ISSUE THREAD

**Issue by philiptaron** [xyproto/tinyxxd#8]
In nixpkgs, we're contemplating switching over from the original Vim-sourced `xxd` to this `xxd`.

- https://github.com/NixOS/nixpkgs/pull/335277

The PR brought [some discussion](https://github.com/NixOS/nixpkgs/pull/335277#discussion_r1720508841) about whether the packaging for `tinyxxd` ought to directly include an alias for `xxd` or whether a secondary output should be used.

The argument for including it is that [Arch packaging](https://gitlab.archlinux.org/archlinux/packaging/packages/tinyxxd/-/blob/main/PKGBUILD?ref_type=heads) does so.

The argument against it is that nothing in this repository (especially the `Makefile`) does anything of the sort.

Could you please clarify in the README your expectation for packagers?

**Comment by xyproto** [comment]
Hi!

* My goal is for this utility to replace `xxd` in connection with Linux/BSD/Homebrew/etc packaging.
* My (perhaps unrealistic) dream is that ViM unbundles `xxd` from ViM and supports this lean standalone fork instead.

I'll update the README too.
