### ISSUE TITLE
Do you plan to track updates in upstream Vim?

### ISSUE THREAD

**Issue by emilazy** [xyproto/tinyxxd#9]
I was trying to diff Vim’s upstream `xxd.c` and your `main.c`, which is unfortunately difficult due to the various clean‐ups you’ve applied (which I appreciate, don’t get me wrong!).

I see that the two recent upstream security issues (https://github.com/vim/vim/commit/67797191e039196128c69ba1538ccaf2a4711323, https://github.com/vim/vim/commit/00221487731ea1868c57259c7aa0eb713cd7ade7) have been fixed in `tinyxxd`, which is great, and that you have ASan‐based testing, which is even better, so I don’t have any specific concerns here about the current state of the codebase, but since it’s not clear from the documentation I wanted to ask if you plan to keep track of changes in Vim’s `src/xxd` (and `runtime/doc/xxd.1`, depending on https://github.com/xyproto/tinyxxd/issues/6?) to backport anything relevant?

**Comment by xyproto** [comment]
No, this is a good point. I should add some sort of alert system for when changes happen to xxd, perhaps with some sort of patch suggestions. I'll see if I can make a utility for this.

**Comment by xyproto** [comment]
I wish there was a tool that could open a GitHub issue when a web page (`https://github.com/vim/vim/commits/master/src/xxd/xxd.c`) changes. Perhaps there is a way to solve this with GitHub actions as well. I'm still looking for solutions and/or contemplating creating a tool.

**Comment by emilazy** [comment]
The best option would probably be to monitor the Git logs. Maybe one of the various GitHub tools that can handle automatically bumping dependencies with logs and diffs would help there. It should be quite easy to write, but I’m not sure if there’s anything turnkey that would immediately fulfil the whole need.

**Comment by Ordoviz** [comment]
For a low-tech solution, you could add https://github.com/vim/vim/commits/master/src/xxd.atom to your RSS feed reader.

**Comment by philiptaron** [comment]
See also:

```
curl -L -H "Accept: application/vnd.github+json" "https://api.github.com/repos/vim/vim/commits?path=src/xxd&since=2024-01-01"
```

**Comment by xyproto** [comment]
I created the [`vigilant`](https://github.com/xyproto/vigilant) utility that now runs on one of my servers and creates pull requests in the `tinyxxd` repository whenever `xxd.c` in the ViM repository changes.
